# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-GoogleMaps
version:      5
version_from: lib/HTML/GoogleMaps.pm
installdirs:  site
requires:
    Geo::Coder::Google:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
