--- #YAML:1.0
name:                HTML-GoogleMaps
version:             6
abstract:            a simple wrapper around the Google Maps API
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Geo::Coder::Google:            0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Nathan Mueller <nate@cs.wisc.edu>
